#!/usr/bin/with-contenv bashio
set -e

bashio::log.info "🔹 Welcome to Network UPS Tools (NUT) Prometheus Exporter"

NUT_EXPORTER_SERVER="$(bashio::config 'NUT_EXPORTER_SERVER')"
NUT_EXPORTER_SERVERPORT="$(bashio::config 'NUT_EXPORTER_SERVERPORT')"
NUT_EXPORTER_USERNAME="$(bashio::config 'NUT_EXPORTER_USERNAME')"
NUT_EXPORTER_PASSWORD="$(bashio::config 'NUT_EXPORTER_PASSWORD')"
NUT_EXPORTER_DISABLE_DEVICE_INFO="$(bashio::config 'NUT_EXPORTER_DISABLE_DEVICE_INFO')"
NUT_EXPORTER_VARIABLES="$(bashio::config 'NUT_EXPORTER_VARIABLES')"
NUT_EXPORTER_ON_REGEX="$(bashio::config 'NUT_EXPORTER_ON_REGEX')"
NUT_EXPORTER_OFF_REGEX="$(bashio::config 'NUT_EXPORTER_OFF_REGEX')"
NUT_EXPORTER_STATUSES="$(bashio::config 'NUT_EXPORTER_STATUSES')"
NUT_EXPORTER_METRICS_NAMESPACE="$(bashio::config 'NUT_EXPORTER_METRICS_NAMESPACE')"
NUT_EXPORTER_WEB_SYSTEMD_SOCKET="$(bashio::config 'NUT_EXPORTER_WEB_SYSTEMD_SOCKET')"
NUT_EXPORTER_WEB_LISTEN_ADDRESS="$(bashio::config 'NUT_EXPORTER_WEB_LISTEN_ADDRESS')"
NUT_EXPORTER_WEB_CONFIG_FILE="$(bashio::config 'NUT_EXPORTER_WEB_CONFIG_FILE')"
NUT_EXPORTER_WEB_TELEMETRY_PATH="$(bashio::config 'NUT_EXPORTER_WEB_TELEMETRY_PATH')"
NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH="$(bashio::config 'NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH')"
NUT_EXPORTER_PRINT_METRICS="$(bashio::config 'NUT_EXPORTER_PRINT_METRICS')"
NUT_EXPORTER_LOG_LEVEL="$(bashio::config 'NUT_EXPORTER_LOG_LEVEL')"
NUT_EXPORTER_LOG_JSON="$(bashio::config 'NUT_EXPORTER_LOG_JSON')"

bashio::log.info "✅ Configuration Loaded:"
[ "${NUT_EXPORTER_SERVER}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_SERVER=$NUT_EXPORTER_SERVER"
[ "${NUT_EXPORTER_SERVERPORT}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_SERVERPORT=$NUT_EXPORTER_SERVERPORT"
[ "${NUT_EXPORTER_USERNAME}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_USERNAME=$NUT_EXPORTER_USERNAME"
[ "${NUT_EXPORTER_PASSWORD}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_PASSWORD=HIDDEN"
[ "${NUT_EXPORTER_DISABLE_DEVICE_INFO}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_DISABLE_DEVICE_INFO=$NUT_EXPORTER_DISABLE_DEVICE_INFO"
[ "${NUT_EXPORTER_VARIABLES}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_VARIABLES=$NUT_EXPORTER_VARIABLES"
[ "${NUT_EXPORTER_ON_REGEX}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_ON_REGEX=$NUT_EXPORTER_ON_REGEX"
[ "${NUT_EXPORTER_OFF_REGEX}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_OFF_REGEX=$NUT_EXPORTER_OFF_REGEX"
[ "${NUT_EXPORTER_STATUSES}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_STATUSES=$NUT_EXPORTER_STATUSES"
[ "${NUT_EXPORTER_METRICS_NAMESPACE}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_METRICS_NAMESPACE=$NUT_EXPORTER_METRICS_NAMESPACE"
[ "${NUT_EXPORTER_WEB_SYSTEMD_SOCKET}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_WEB_SYSTEMD_SOCKET=$NUT_EXPORTER_WEB_SYSTEMD_SOCKET"
[ "${NUT_EXPORTER_WEB_LISTEN_ADDRESS}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_WEB_LISTEN_ADDRESS=$NUT_EXPORTER_WEB_LISTEN_ADDRESS"
[ "${NUT_EXPORTER_WEB_CONFIG_FILE}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_WEB_CONFIG_FILE=$NUT_EXPORTER_WEB_CONFIG_FILE"
[ "${NUT_EXPORTER_WEB_TELEMETRY_PATH}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_WEB_TELEMETRY_PATH=$NUT_EXPORTER_WEB_TELEMETRY_PATH"
[ "${NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH=$NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH"
[ "${NUT_EXPORTER_PRINT_METRICS}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_PRINT_METRICS=$NUT_EXPORTER_PRINT_METRICS"
[ "${NUT_EXPORTER_LOG_LEVEL}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_LOG_LEVEL=$NUT_EXPORTER_LOG_LEVEL"
[ "${NUT_EXPORTER_LOG_JSON}" != "null" ] && \
    bashio::log.info "  NUT_EXPORTER_LOG_JSON=$NUT_EXPORTER_LOG_JSON"

while true; do
    bashio::log.info "🔹 Starting NUT Exporter..."
    # Custom variables are already exported above
    [ "${NUT_EXPORTER_SERVER}" != "null" ] && export NUT_EXPORTER_SERVER="$NUT_EXPORTER_SERVER"
    [ "${NUT_EXPORTER_SERVERPORT}" != "null" ] && export NUT_EXPORTER_SERVERPORT="$NUT_EXPORTER_SERVERPORT"
    [ "${NUT_EXPORTER_USERNAME}" != "null" ] && export NUT_EXPORTER_USERNAME="$NUT_EXPORTER_USERNAME"
    [ "${NUT_EXPORTER_PASSWORD}" != "null" ] && export NUT_EXPORTER_PASSWORD="$NUT_EXPORTER_PASSWORD"
    [ "${NUT_EXPORTER_DISABLE_DEVICE_INFO}" != "null" ] && export NUT_EXPORTER_DISABLE_DEVICE_INFO="$NUT_EXPORTER_DISABLE_DEVICE_INFO"
    [ "${NUT_EXPORTER_VARIABLES}" != "null" ] && export NUT_EXPORTER_VARIABLES="$NUT_EXPORTER_VARIABLES"
    [ "${NUT_EXPORTER_ON_REGEX}" != "null" ] && export NUT_EXPORTER_ON_REGEX="$NUT_EXPORTER_ON_REGEX"
    [ "${NUT_EXPORTER_OFF_REGEX}" != "null" ] && export NUT_EXPORTER_OFF_REGEX="$NUT_EXPORTER_OFF_REGEX"
    [ "${NUT_EXPORTER_STATUSES}" != "null" ] && export NUT_EXPORTER_STATUSES="$NUT_EXPORTER_STATUSES"
    [ "${NUT_EXPORTER_METRICS_NAMESPACE}" != "null" ] && export NUT_EXPORTER_METRICS_NAMESPACE="$NUT_EXPORTER_METRICS_NAMESPACE"
    [ "${NUT_EXPORTER_WEB_SYSTEMD_SOCKET}" != "null" ] && export NUT_EXPORTER_WEB_SYSTEMD_SOCKET="$NUT_EXPORTER_WEB_SYSTEMD_SOCKET"
    [ "${NUT_EXPORTER_WEB_LISTEN_ADDRESS}" != "null" ] && export NUT_EXPORTER_WEB_LISTEN_ADDRESS="$NUT_EXPORTER_WEB_LISTEN_ADDRESS"
    [ "${NUT_EXPORTER_WEB_CONFIG_FILE}" != "null" ] && export NUT_EXPORTER_WEB_CONFIG_FILE="$NUT_EXPORTER_WEB_CONFIG_FILE"
    [ "${NUT_EXPORTER_WEB_TELEMETRY_PATH}" != "null" ] && export NUT_EXPORTER_WEB_TELEMETRY_PATH="$NUT_EXPORTER_WEB_TELEMETRY_PATH"
    [ "${NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH}" != "null" ] && export NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH="$NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH"
    [ "${NUT_EXPORTER_PRINT_METRICS}" != "null" ] && export NUT_EXPORTER_PRINT_METRICS="$NUT_EXPORTER_PRINT_METRICS"
    [ "${NUT_EXPORTER_LOG_LEVEL}" != "null" ] && export NUT_EXPORTER_LOG_LEVEL="$NUT_EXPORTER_LOG_LEVEL"
    [ "${NUT_EXPORTER_LOG_JSON}" != "null" ] && export NUT_EXPORTER_LOG_JSON="$NUT_EXPORTER_LOG_JSON"
    /app/nut_exporter

    bashio::log.warning "Exporter stopped! Waiting 5 second before reconnecting..."
    sleep 5;
done
